import { randomUUID } from 'node:crypto';
import { lstat, open, readFile, rename } from 'node:fs/promises';
import { isIP } from 'node:net';
import { basename, dirname, isAbsolute, join } from 'node:path';

const MAX_CONFIG_BYTES = 128 * 1024;
const MAX_SECRET_BYTES = 4 * 1024;

export interface KamailioListener {
  host: string;
  port: number;
  advertise?: KamailioAdvertisedAddress;
}

export interface KamailioAdvertisedAddress {
  host: string;
  port: number;
}

export interface KamailioTlsConfig {
  private_key_file: string;
  certificate_file: string;
  ca_file: string;
  require_client_certificate: boolean;
}

export interface KamailioConfig {
  schema_version: '1.0.0';
  region_id: string;
  zone_id: string;
  cell_id: string;
  cell_lease_epoch: number;
  default_pool_id: number;
  dispatcher_file: string;
  tls_config_file: string;
  udp_listener: KamailioListener;
  tcp_listener: KamailioListener;
  tls_listener: KamailioListener;
  wss_listener: KamailioListener;
  rpc_listener: KamailioListener;
  trusted_source_cidrs: string[];
  allow_public_wss: boolean;
  max_message_bytes: number;
  per_source_invite_cps: number;
  global_invite_cps: number;
  pike_sampling_seconds: number;
  pike_request_density: number;
  max_failovers: number;
  retry_after_seconds: number;
  tls: KamailioTlsConfig;
}

export interface KamailioConfigSecrets {
  topoh_mask_key: string;
  rpc_bearer_token: string;
}

export interface RenderedKamailioConfig {
  kamailio_cfg: string;
  tls_cfg: string;
}

export interface KamailioConfigRuntime {
  config: KamailioConfig;
  secrets: KamailioConfigSecrets;
  output_file: string;
  tls_output_file: string;
}

export function renderKamailioConfig(
  rawConfig: KamailioConfig,
  rawSecrets: KamailioConfigSecrets
): RenderedKamailioConfig {
  const config = validateConfig(rawConfig);
  const secrets = validateSecrets(rawSecrets);
  const trustedExpression = config.trusted_source_cidrs
    .map((cidr) => `is_in_subnet("$si", "${kamailioString(cidr)}")`)
    .join(' || ');
  const publicWssExpression = config.allow_public_wss
    ? ' || $proto == "WSS"'
    : '';

  const kamailioCfg = `#!KAMAILIO
# Generated by iveKit. Contains secret material; mode must remain 0600.

debug=2
log_stderror=yes
children=8
tcp_children=8
auto_aliases=no
server_header="Server: ivekit-sip-edge"
user_agent_header="User-Agent: ivekit-sip-edge"
enable_tls=yes
tcp_accept_no_cl=yes
tcp_connection_lifetime=3605

listen=udp:${listener(config.udp_listener)}
listen=tcp:${listener(config.tcp_listener)}
listen=tls:${listener(config.tls_listener)}
listen=tls:${listener(config.wss_listener)}
listen=tcp:${listener(config.rpc_listener)}

loadmodule "kex.so"
loadmodule "corex.so"
loadmodule "tm.so"
loadmodule "tmx.so"
loadmodule "sl.so"
loadmodule "rr.so"
loadmodule "pv.so"
loadmodule "maxfwd.so"
loadmodule "textops.so"
loadmodule "siputils.so"
loadmodule "xlog.so"
loadmodule "sanity.so"
loadmodule "nathelper.so"
loadmodule "dispatcher.so"
loadmodule "dialog.so"
loadmodule "topoh.so"
loadmodule "pike.so"
loadmodule "htable.so"
loadmodule "ipops.so"
loadmodule "xhttp.so"
loadmodule "jsonrpcs.so"
loadmodule "websocket.so"
loadmodule "tls.so"
loadmodule "statistics.so"
loadmodule "xhttp_prom.so"

modparam("tm", "failure_reply_mode", 3)
modparam("tm", "fr_timer", 30000)
modparam("tm", "fr_inv_timer", 120000)
modparam("rr", "append_fromtag", 1)
modparam("rr", "enable_full_lr", 1)
modparam("rr", "enable_double_rr", 2)

modparam("dispatcher", "list_file", "${kamailioString(config.dispatcher_file)}")
modparam("dispatcher", "flags", 2)
modparam("dispatcher", "xavp_dst", "_dsdst_")
modparam("dispatcher", "xavp_ctx", "_dsctx_")
modparam("dispatcher", "ds_ping_method", "OPTIONS")
modparam("dispatcher", "ds_ping_interval", 2)
modparam("dispatcher", "ds_ping_fr_timer", 500)
modparam("dispatcher", "ds_probing_threshold", 3)
modparam("dispatcher", "ds_inactive_threshold", 2)
modparam("dispatcher", "ds_probing_mode", 1)
modparam("dispatcher", "ds_ping_reply_codes", "class=2;code=404")

modparam("dialog", "default_timeout", 14400)
modparam("dialog", "dlg_match_mode", 1)
modparam("topoh", "mask_key", "${kamailioString(secrets.topoh_mask_key)}")
modparam("topoh", "mask_ip", "127.0.0.8")

modparam("pike", "sampling_time_unit", ${config.pike_sampling_seconds})
modparam("pike", "reqs_density_per_unit", ${config.pike_request_density})
modparam("htable", "htable", "ivekit_source_cps=>size=14;autoexpire=5;")
modparam("htable", "htable", "ivekit_global_cps=>size=2;autoexpire=5;")

modparam("tls", "config", "${kamailioString(config.tls_config_file)}")
modparam("jsonrpcs", "transport", 1)
modparam("jsonrpcs", "pretty_format", 0)
modparam("xhttp_prom", "xhttp_prom_stats", "all")
modparam("statistics", "variable", "ivekit_new_invites")
modparam("statistics", "variable", "ivekit_dispatch_failures")
modparam("statistics", "variable", "ivekit_failovers")
modparam("statistics", "variable", "ivekit_pin_failures")

request_route {
    route(REQINIT);

    if (is_method("CANCEL")) {
        if (t_check_trans()) route(RELAY);
        exit;
    }

    if (!is_method("ACK")) {
        if (t_precheck_trans()) {
            t_check_trans();
            exit;
        }
        t_check_trans();
    }

    route(AUTH);

    if (has_totag()) route(WITHINDLG);
    if (is_method("INVITE")) route(NEW_INVITE);
    if (is_method("REGISTER")) {
        $var(pool) = ${config.default_pool_id};
        route(DISPATCH);
    }

    sl_send_reply("405", "Method Not Allowed");
    exit;
}

route[REQINIT] {
    if ($ml > ${config.max_message_bytes}) {
        sl_send_reply("513", "Message Too Large");
        exit;
    }
    if (!mf_process_maxfwd_header("16")) {
        sl_send_reply("483", "Too Many Hops");
        exit;
    }
    if (!sanity_check("17895", "7")) {
        sl_send_reply("400", "Malformed SIP Message");
        exit;
    }
    if (is_method("OPTIONS") && uri == myself && $rU == $null) {
        sl_send_reply("200", "OK");
        exit;
    }
    if (!is_method("INVITE|ACK|CANCEL|BYE|UPDATE|INFO|PRACK|REFER|OPTIONS|REGISTER")) {
        sl_send_reply("405", "Method Not Allowed");
        exit;
    }
}

route[AUTH] {
    # Every external X-IveKit header is untrusted. Recreate only after placement.
    remove_hf("X-IveKit-Node-ID");
    remove_hf("X-IveKit-Pin-Set");
    remove_hf("X-IveKit-Cell-ID");
    remove_hf("X-IveKit-Cell-Lease-Epoch");
    remove_hf("X-IveKit-Edge-Schema");

    $var(trusted_source) = 0;
    if (${trustedExpression}${publicWssExpression}) $var(trusted_source) = 1;
    if ($var(trusted_source) != 1) {
        sl_send_reply("403", "Forbidden");
        exit;
    }

    # Public WSS credentials and trusted-trunk digest/mTLS are verified by RustPBX.
    if (is_method("REGISTER") && $proto != "WSS" && $proto != "TLS" &&
            !(${trustedExpression})) {
        sl_send_reply("403", "Secure Registration Required");
        exit;
    }

    if (is_method("INVITE") && !has_totag()) {
        if (!pike_check_req()) {
            append_to_reply("Retry-After: ${config.retry_after_seconds}\\r\\n");
            sl_send_reply("503", "Rate Limited");
            exit;
        }

        $var(source_second_key) = $si + "::second";
        $var(source_count_key) = $si + "::count";
        if ($sht(ivekit_source_cps=>$var(source_second_key)) != $Ts) {
            $sht(ivekit_source_cps=>$var(source_second_key)) = $Ts;
            $sht(ivekit_source_cps=>$var(source_count_key)) = 0;
        }
        $sht(ivekit_source_cps=>$var(source_count_key)) =
            $sht(ivekit_source_cps=>$var(source_count_key)) + 1;
        if ($sht(ivekit_source_cps=>$var(source_count_key)) > ${config.per_source_invite_cps}) {
            append_to_reply("Retry-After: ${config.retry_after_seconds}\\r\\n");
            sl_send_reply("503", "Source CPS Exceeded");
            exit;
        }

        if ($sht(ivekit_global_cps=>second) != $Ts) {
            $sht(ivekit_global_cps=>second) = $Ts;
            $sht(ivekit_global_cps=>count) = 0;
        }
        $sht(ivekit_global_cps=>count) = $sht(ivekit_global_cps=>count) + 1;
        if ($sht(ivekit_global_cps=>count) > ${config.global_invite_cps}) {
            append_to_reply("Retry-After: ${config.retry_after_seconds}\\r\\n");
            sl_send_reply("503", "Cell CPS Exceeded");
            exit;
        }
    }
}

route[WITHINDLG] {
    if (!has_totag()) return;
    if (is_method("ACK") && t_check_trans()) {
        route(RELAY);
        exit;
    }
    if (!loose_route()) {
        sl_send_reply("481", "Dialog Route Missing");
        exit;
    }

    $var(pinset) = $(route_uri{uri.param,ivkpin});
    $var(pin_epoch) = $(route_uri{uri.param,ivkep});
    if ($var(pinset) == $null || $var(pinset) !~ "^[1-9][0-9]{0,8}$" ||
            $var(pin_epoch) != "${config.cell_lease_epoch}") {
        update_stat("ivekit_pin_failures", "+1");
        sl_send_reply("481", "Invalid Dialog Owner");
        exit;
    }
    if (!ds_select_dst("$var(pinset)", "0", "1")) {
        update_stat("ivekit_pin_failures", "+1");
        append_to_reply("Retry-After: ${config.retry_after_seconds}\\r\\n");
        sl_send_reply("503", "Dialog Owner Unavailable");
        exit;
    }
    route(READ_DISPATCHER_OWNER);
    route(INTERNAL_HEADERS);
    route(RELAY);
}

route[NEW_INVITE] {
    update_stat("ivekit_new_invites", "+1");
    $var(pool) = ${config.default_pool_id};
    route(DISPATCH);
}

route[DISPATCH] {
    if (!ds_select_dst("$var(pool)", "11", "${config.max_failovers}")) {
        update_stat("ivekit_dispatch_failures", "+1");
        append_to_reply("Retry-After: ${config.retry_after_seconds}\\r\\n");
        sl_send_reply("503", "No Capacity");
        exit;
    }
    route(READ_DISPATCHER_OWNER);

    if (is_method("INVITE")) {
        dlg_manage();
        $dlg_var(ivekit_pin_set) = $var(pinset);
        $dlg_var(ivekit_node_id) = $var(node_id);
        $dlg_var(ivekit_cell_epoch) = ${config.cell_lease_epoch};
        record_route(";ivkpin=$var(pinset);ivkep=${config.cell_lease_epoch};ivks=1");
        t_on_failure("RUSTPBX_FAILOVER");
    }
    route(INTERNAL_HEADERS);
    route(RELAY);
}

route[READ_DISPATCHER_OWNER] {
    $var(pinset) = $(xavp(_dsdst_=>attrs){param.value,pinset});
    $var(node_id) = $(xavp(_dsdst_=>attrs){param.value,node});
    if ($var(pinset) == $null || $var(pinset) !~ "^[1-9][0-9]{0,8}$" ||
            $var(node_id) == $null || $var(node_id) !~ "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$") {
        update_stat("ivekit_dispatch_failures", "+1");
        sl_send_reply("503", "Invalid Route Snapshot");
        exit;
    }
}

route[INTERNAL_HEADERS] {
    remove_hf("X-IveKit-Node-ID");
    remove_hf("X-IveKit-Pin-Set");
    remove_hf("X-IveKit-Cell-ID");
    remove_hf("X-IveKit-Cell-Lease-Epoch");
    remove_hf("X-IveKit-Edge-Schema");
    append_hf("X-IveKit-Node-ID: $var(node_id)\\r\\n");
    append_hf("X-IveKit-Pin-Set: $var(pinset)\\r\\n");
    append_hf("X-IveKit-Cell-ID: ${kamailioString(config.cell_id)}\\r\\n");
    append_hf("X-IveKit-Cell-Lease-Epoch: ${config.cell_lease_epoch}\\r\\n");
    append_hf("X-IveKit-Edge-Schema: 1\\r\\n");
}

route[RELAY] {
    if (!t_relay()) sl_reply_error();
    exit;
}

failure_route[RUSTPBX_FAILOVER] {
    if (t_is_canceled()) exit;
    if (!t_branch_timeout() && !t_check_status("408|500|502|503|504")) exit;

    ds_mark_dst("tp");
    if (ds_next_dst()) {
        update_stat("ivekit_failovers", "+1");
        route(READ_DISPATCHER_OWNER);
        remove_record_route();
        record_route(";ivkpin=$var(pinset);ivkep=${config.cell_lease_epoch};ivks=1");
        $dlg_var(ivekit_pin_set) = $var(pinset);
        $dlg_var(ivekit_node_id) = $var(node_id);
        route(INTERNAL_HEADERS);
        t_on_failure("RUSTPBX_FAILOVER");
        if (!t_relay()) sl_reply_error();
        exit;
    }

    update_stat("ivekit_dispatch_failures", "+1");
    append_to_reply("Retry-After: ${config.retry_after_seconds}\\r\\n");
    t_reply("503", "No Capacity");
    exit;
}

event_route[xhttp:request] {
    if ($Rp == ${config.rpc_listener.port} && $si == "127.0.0.1") {
        if ($hu == "/metrics") {
            prom_dispatch();
            exit;
        }
        if ($hu == "/RPC") {
            if ($hdr(Authorization) != "Bearer ${kamailioString(secrets.rpc_bearer_token)}") {
                xhttp_reply("403", "Forbidden", "text/plain", "forbidden\\n");
                exit;
            }
            jsonrpc_dispatch();
            exit;
        }
        xhttp_reply("404", "Not Found", "text/plain", "not found\\n");
        exit;
    }

    if ($Rp == ${config.wss_listener.port} && $hu =~ "^/ws($|[?])") {
        if (ws_handle_handshake()) exit;
        xhttp_reply("400", "Bad Request", "text/plain", "websocket required\\n");
        exit;
    }

    xhttp_reply("403", "Forbidden", "text/plain", "forbidden\\n");
    exit;
}

event_route[dispatcher:dst-down] {
    xlog("L_WARN", "ivekit dispatcher destination became unavailable\\n");
}

event_route[dispatcher:dst-up] {
    xlog("L_INFO", "ivekit dispatcher destination recovered\\n");
}
`;

  const tlsCfg = `[server:default]
method = TLSv1.2+
verify_certificate = ${config.tls.require_client_certificate ? 'yes' : 'no'}
require_certificate = ${config.tls.require_client_certificate ? 'yes' : 'no'}
private_key = ${config.tls.private_key_file}
certificate = ${config.tls.certificate_file}
ca_list = ${config.tls.ca_file}
`;

  return { kamailio_cfg: kamailioCfg, tls_cfg: tlsCfg };
}

export async function loadKamailioConfigRuntime(
  env: NodeJS.ProcessEnv = process.env
): Promise<KamailioConfigRuntime> {
  rejectInlineSecrets(env);
  const configFile = requiredAbsoluteEnv(env, 'OPC_IVEKIT_KAMAILIO_CONFIG_FILE');
  const topohFile = requiredAbsoluteEnv(env, 'OPC_IVEKIT_KAMAILIO_TOPOH_KEY_FILE');
  const rpcFile = requiredAbsoluteEnv(env, 'OPC_IVEKIT_KAMAILIO_RPC_TOKEN_FILE');
  const outputFile = requiredAbsoluteEnv(env, 'OPC_IVEKIT_KAMAILIO_OUTPUT_FILE');
  const tlsOutputFile = requiredAbsoluteEnv(env, 'OPC_IVEKIT_KAMAILIO_TLS_OUTPUT_FILE');
  const rawConfig = JSON.parse(await readBoundedFile(configFile, MAX_CONFIG_BYTES)) as KamailioConfig;
  const config = validateConfig(rawConfig);
  if (config.tls_config_file !== tlsOutputFile) {
    throw new Error('tls_config_file must match OPC_IVEKIT_KAMAILIO_TLS_OUTPUT_FILE');
  }
  const secrets = validateSecrets({
    topoh_mask_key: (await readBoundedFile(topohFile, MAX_SECRET_BYTES, true)).trim(),
    rpc_bearer_token: (await readBoundedFile(rpcFile, MAX_SECRET_BYTES, true)).trim()
  });
  return {
    config,
    secrets,
    output_file: outputFile,
    tls_output_file: tlsOutputFile
  };
}

export async function writeKamailioConfigRuntime(runtime: KamailioConfigRuntime): Promise<void> {
  const rendered = renderKamailioConfig(runtime.config, runtime.secrets);
  await atomicWrite(runtime.output_file, rendered.kamailio_cfg, 0o600);
  await atomicWrite(runtime.tls_output_file, rendered.tls_cfg, 0o600);
}

function validateConfig(value: KamailioConfig): KamailioConfig {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('invalid Kamailio config');
  assertExactKeys(value as unknown as Record<string, unknown>, [
    'allow_public_wss', 'cell_id', 'cell_lease_epoch', 'default_pool_id',
    'dispatcher_file', 'global_invite_cps', 'max_failovers', 'max_message_bytes',
    'per_source_invite_cps', 'pike_request_density', 'pike_sampling_seconds',
    'region_id', 'retry_after_seconds', 'rpc_listener', 'schema_version',
    'tcp_listener', 'tls', 'tls_config_file', 'tls_listener', 'trusted_source_cidrs', 'udp_listener',
    'wss_listener', 'zone_id'
  ], 'Kamailio config');
  if (value.schema_version !== '1.0.0') throw new Error('unsupported Kamailio config schema_version');
  for (const [name, id] of [
    ['region_id', value.region_id], ['zone_id', value.zone_id], ['cell_id', value.cell_id]
  ] as const) assertIdentifier(id, name);
  assertInteger(value.cell_lease_epoch, 1, 0xffff_ffff, 'cell_lease_epoch');
  assertInteger(value.default_pool_id, 1, 999_999_999, 'default_pool_id');
  assertAbsolutePath(value.dispatcher_file, 'dispatcher_file');
  assertAbsolutePath(value.tls_config_file, 'tls_config_file');
  validateListener(value.udp_listener, 'udp_listener', true);
  validateListener(value.tcp_listener, 'tcp_listener', true);
  validateListener(value.tls_listener, 'tls_listener', true);
  validateListener(value.wss_listener, 'wss_listener', true);
  validateListener(value.rpc_listener, 'rpc_listener', false);
  if (!isLoopback(value.rpc_listener.host)) throw new Error('rpc_listener must be loopback-only');
  const listenerKeys = [
    `udp:${value.udp_listener.host}:${value.udp_listener.port}`,
    `tcp:${value.tcp_listener.host}:${value.tcp_listener.port}`,
    `tls:${value.tls_listener.host}:${value.tls_listener.port}`,
    `tls:${value.wss_listener.host}:${value.wss_listener.port}`,
    `tcp:${value.rpc_listener.host}:${value.rpc_listener.port}`
  ];
  if (new Set(listenerKeys).size !== listenerKeys.length) throw new Error('Kamailio listeners must be distinct');
  if (!Array.isArray(value.trusted_source_cidrs) || value.trusted_source_cidrs.length < 1 ||
      value.trusted_source_cidrs.length > 256) throw new Error('trusted_source_cidrs is invalid');
  for (const cidr of value.trusted_source_cidrs) validateCidr(cidr);
  if (typeof value.allow_public_wss !== 'boolean') throw new Error('allow_public_wss is invalid');
  assertInteger(value.max_message_bytes, 4_096, 1_048_576, 'max_message_bytes');
  assertInteger(value.per_source_invite_cps, 1, 100_000, 'per_source_invite_cps');
  assertInteger(value.global_invite_cps, value.per_source_invite_cps, 1_000_000, 'global_invite_cps');
  assertInteger(value.pike_sampling_seconds, 1, 60, 'pike_sampling_seconds');
  assertInteger(value.pike_request_density, 1, 1_000_000, 'pike_request_density');
  assertInteger(value.max_failovers, 1, 32, 'max_failovers');
  assertInteger(value.retry_after_seconds, 1, 300, 'retry_after_seconds');
  validateTls(value.tls);
  return value;
}

function validateTls(value: KamailioTlsConfig) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('tls is invalid');
  assertExactKeys(value as unknown as Record<string, unknown>, [
    'ca_file', 'certificate_file', 'private_key_file', 'require_client_certificate'
  ], 'tls');
  assertAbsolutePath(value.private_key_file, 'tls.private_key_file');
  assertAbsolutePath(value.certificate_file, 'tls.certificate_file');
  assertAbsolutePath(value.ca_file, 'tls.ca_file');
  if (typeof value.require_client_certificate !== 'boolean') {
    throw new Error('tls.require_client_certificate is invalid');
  }
}

function validateSecrets(value: KamailioConfigSecrets): KamailioConfigSecrets {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('invalid Kamailio secrets');
  assertExactKeys(value as unknown as Record<string, unknown>, [
    'rpc_bearer_token', 'topoh_mask_key'
  ], 'Kamailio secrets');
  for (const [name, secret] of [
    ['topoh_mask_key', value.topoh_mask_key], ['rpc_bearer_token', value.rpc_bearer_token]
  ] as const) {
    if (typeof secret !== 'string' || secret.length < 32 || secret.length > 256 ||
        !/^[A-Za-z0-9._~+\/-]+$/.test(secret)) throw new Error(`${name} is invalid`);
  }
  if (value.topoh_mask_key === value.rpc_bearer_token) {
    throw new Error('Kamailio secrets must be distinct');
  }
  return value;
}

function validateListener(value: KamailioListener, name: string, publicListener: boolean) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${name} is invalid`);
  assertExactKeys(
    value as unknown as Record<string, unknown>,
    publicListener ? ['advertise', 'host', 'port'] : ['host', 'port'],
    name
  );
  if (typeof value.host !== 'string' || (!isIP(value.host) && value.host !== 'localhost')) {
    throw new Error(`${name}.host is invalid`);
  }
  assertInteger(value.port, 1, 65_535, `${name}.port`);
  if (publicListener) {
    const advertise = value.advertise;
    if (!advertise || typeof advertise !== 'object' || Array.isArray(advertise)) {
      throw new Error(`${name}.advertise is required`);
    }
    assertExactKeys(advertise as unknown as Record<string, unknown>, ['host', 'port'], `${name}.advertise`);
    if (!validNetworkHost(advertise.host) || advertise.host === '0.0.0.0' || advertise.host === '::') {
      throw new Error(`${name}.advertise.host is invalid`);
    }
    assertInteger(advertise.port, 1, 65_535, `${name}.advertise.port`);
  } else if (value.advertise !== undefined) {
    throw new Error(`${name} must not advertise a public address`);
  }
}

function validateCidr(value: string) {
  if (typeof value !== 'string' || value.length > 64) throw new Error('trusted_source_cidrs is invalid');
  const parts = value.split('/');
  if (parts.length !== 2 || !isIP(parts[0]!)) throw new Error(`invalid trusted CIDR: ${value}`);
  const version = isIP(parts[0]!);
  const prefix = Number(parts[1]);
  const maximum = version === 4 ? 32 : 128;
  if (!Number.isInteger(prefix) || prefix < 0 || prefix > maximum) {
    throw new Error(`invalid trusted CIDR: ${value}`);
  }
  if (prefix === 0) throw new Error(`wildcard trusted CIDR is forbidden: ${value}`);
}

function assertIdentifier(value: unknown, name: string) {
  if (typeof value !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value)) {
    throw new Error(`${name} is invalid`);
  }
}

function assertInteger(value: unknown, minimum: number, maximum: number, name: string) {
  if (!Number.isSafeInteger(value) || Number(value) < minimum || Number(value) > maximum) {
    throw new Error(`${name} is invalid`);
  }
}

function assertAbsolutePath(value: unknown, name: string) {
  if (typeof value !== 'string' || !isAbsolute(value) || value.length > 1024 || /[\r\n"\\]/.test(value)) {
    throw new Error(`${name} is invalid`);
  }
}

function assertExactKeys(value: Record<string, unknown>, keys: string[], name: string) {
  const actual = Object.keys(value).sort();
  const expected = [...keys].sort();
  if (actual.length !== expected.length || actual.some((key, index) => key !== expected[index])) {
    throw new Error(`${name} contains unexpected or missing fields`);
  }
}

function listener(value: KamailioListener) {
  const bind = value.host.includes(':') ? `[${value.host}]:${value.port}` : `${value.host}:${value.port}`;
  if (!value.advertise) return bind;
  const advertisedHost = value.advertise.host.includes(':')
    ? `[${value.advertise.host}]`
    : value.advertise.host;
  return `${bind} advertise ${advertisedHost}:${value.advertise.port}`;
}

function validNetworkHost(value: unknown): value is string {
  if (typeof value !== 'string' || value.length < 1 || value.length > 253) return false;
  if (isIP(value)) return true;
  return value.split('.').every((label) =>
    /^[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$/.test(label)
  );
}

function isLoopback(host: string) {
  return host === '127.0.0.1' || host === '::1' || host === 'localhost';
}

function kamailioString(value: string) {
  if (/[\r\n"\\]/.test(value)) throw new Error('unsafe Kamailio string');
  return value;
}

function rejectInlineSecrets(env: NodeJS.ProcessEnv) {
  const forbidden = [
    'OPC_IVEKIT_KAMAILIO_TOPOH_KEY',
    'OPC_IVEKIT_KAMAILIO_RPC_TOKEN'
  ];
  if (forbidden.some((name) => env[name] !== undefined)) {
    throw new Error('inline Kamailio secret variables are forbidden');
  }
}

function requiredAbsoluteEnv(env: NodeJS.ProcessEnv, name: string) {
  const value = env[name];
  if (!value || !isAbsolute(value) || value.length > 1024) throw new Error(`${name} must be an absolute path`);
  return value;
}

async function readBoundedFile(path: string, maximum: number, secret = false) {
  const metadata = await lstat(path);
  if (!metadata.isFile() || metadata.isSymbolicLink() || metadata.size < 1 || metadata.size > maximum) {
    throw new Error(`${basename(path)} is not a bounded regular file`);
  }
  if (secret && (metadata.mode & 0o022) !== 0) throw new Error(`${basename(path)} has unsafe permissions`);
  return readFile(path, 'utf8');
}

async function atomicWrite(path: string, contents: string, mode: number) {
  const directory = dirname(path);
  const temporary = join(directory, `.${basename(path)}.${randomUUID()}.tmp`);
  const handle = await open(temporary, 'wx', mode);
  try {
    await handle.writeFile(contents, 'utf8');
    await handle.sync();
  } finally {
    await handle.close();
  }
  await rename(temporary, path);
  const directoryHandle = await open(directory, 'r');
  try {
    await directoryHandle.sync();
  } finally {
    await directoryHandle.close();
  }
}
