{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: converact-rtpengine
  labels:
    app.kubernetes.io/name: converact-rtpengine
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: converact-rtpengine
{{- end }}
