apiVersion: v1
kind: Service
metadata:
  name: converact-rtpengine
  labels:
    app.kubernetes.io/name: converact-rtpengine
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: converact-rtpengine
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
    - name: media-control
      port: 3211
      targetPort: media-control
      protocol: TCP
