import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import { platformPayloadDigest } from '../src/agent-runtime/converact/platform-foundation/event-envelope.js';

test('Rust canonical vectors are generated by the active TypeScript contract', () => {
  const fixture = JSON.parse(readFileSync(
    new URL('../server-rs/tests/fixtures/canonical-json-v1.json', import.meta.url),
    'utf8'
  )) as {
    source: string;
    vectors: Array<{ name: string; input: unknown; canonical: string; sha256: string }>;
  };

  assert.equal(
    fixture.source,
    'src/agent-runtime/converact/platform-foundation/event-envelope.ts#platformPayloadDigest'
  );
  assert.equal(fixture.vectors.length >= 3, true);
  for (const vector of fixture.vectors) {
    assert.equal(platformPayloadDigest(vector.input), vector.sha256, vector.name);
    assert.equal(
      createHash('sha256').update(vector.canonical, 'utf8').digest('hex'),
      vector.sha256,
      `${vector.name}: canonical bytes`
    );
  }
});
