{{- if .Values.tinode.enabled }}
{{- include "converact.tinodeValidate" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "converact.tinodeFullname" . }}
  labels:
    {{- include "converact.labels" . | nindent 4 }}
    app.kubernetes.io/component: tinode
data:
  STORE_USE_ADAPTER: postgres
  RESET_DB: "false"
  WEBRTC_ENABLED: "false"
  SAMPLE_DATA: ""
  UPGRADE_DB: {{ .Values.tinode.config.upgradeDatabase | quote }}
  ACC_GC_ENABLED: {{ .Values.tinode.config.accountGarbageCollectionEnabled | quote }}
  SERVER_STATUS_PATH: /health
{{- end }}
