{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ivekit-homer.fullname" . }}
  labels:
    {{- include "ivekit-homer.labels" . | nindent 4 }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "ivekit-homer.selectorLabels" . | nindent 6 }}
{{- end }}
