apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: converact-victoria-metrics-data
  labels:
    app.kubernetes.io/name: converact-victoria-metrics
    app.kubernetes.io/component: metrics-storage
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 200Gi
