apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: converact-otel-collector
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: converact-otel-collector
      app.kubernetes.io/component: trace-gateway
