apiVersion: v1
kind: Service
metadata:
  name: ivekit-otel-collector
  labels:
    app.kubernetes.io/name: ivekit-otel-collector
    app.kubernetes.io/component: trace-gateway
spec:
  selector:
    app.kubernetes.io/name: ivekit-otel-collector
    app.kubernetes.io/component: trace-gateway
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: metrics
      port: 8888
      targetPort: metrics
    - name: health
      port: 13133
      targetPort: health
