[general]
static=yes
writeprotect=yes

[from-rustpbx]
exten => uas,1,NoOp(Converact G03 real peer received ${CALLERID(all)})
 same => n,Answer()
 same => n,Wait(30)
 same => n,Hangup()

exten => h,1,NoOp(Converact G03 real peer call completed)
