[global]
type=global
user_agent=Converact-G03-Asterisk-20.6.0
endpoint_identifier_order=ip

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=172.30.44.0/24

[rustpbx]
type=endpoint
transport=transport-udp
context=from-rustpbx
disallow=all
allow=ulaw
direct_media=no
rtp_symmetric=no
force_rport=no
rewrite_contact=no
timers=no

[rustpbx-identify]
type=identify
endpoint=rustpbx
match=172.30.44.10
