import type { IntegrationCatalogEntry } from './provider-runtime-types.js';

export const defaultIntegrationCatalog: IntegrationCatalogEntry[] = [
  {
    id: 'opc-native-crm',
    name: 'OPC Native CRM',
    category: 'crm',
    source_type: 'internal',
    license: 'internal',
    maturity: 'stable',
    stability_score: 92,
    default_risk_level: 'R2',
    deployment_modes: ['built_in'],
    capabilities: ['contacts', 'leads', 'opportunities', 'tasks', 'timeline'],
    recommended_use: 'Default CRM for one-person-company workflows; keep UX light and use external CRMs only as adapters.',
    caution_notes: 'Do not replace with a heavy CRM unless the tenant explicitly needs mature CRM operations.',
    adapter_status: 'native',
    adoption_tier: 'core'
  },
  {
    id: 'opc-native-wiki',
    name: 'OPC Native Wiki',
    category: 'knowledge_base',
    source_type: 'internal',
    license: 'internal',
    maturity: 'stable',
    stability_score: 90,
    default_risk_level: 'R2',
    deployment_modes: ['built_in'],
    capabilities: ['llm_wiki', 'knowledge_sources', 'markdown_pages', 'wiki_index', 'wiki_lint'],
    recommended_use: 'Default knowledge-base foundation using immutable sources, generated wiki pages, index/log, query, and lint.',
    caution_notes: 'Keep raw sources immutable and route page updates through harness tools, audit, and checkpoints.',
    adapter_status: 'native',
    adoption_tier: 'core'
  },
  {
    id: 'twenty-crm',
    name: 'Twenty CRM',
    category: 'crm',
    source_type: 'open_source',
    license: 'AGPL-3.0',
    maturity: 'active',
    stability_score: 78,
    default_risk_level: 'R2',
    deployment_modes: ['self_hosted', 'docker'],
    capabilities: ['contacts', 'companies', 'opportunities', 'tasks', 'custom_objects'],
    recommended_use: 'Modern lightweight CRM reference and optional self-hosted CRM backend for OPC.',
    caution_notes: 'AGPL license requires careful commercial compliance review before embedding.',
    adapter_status: 'voice_adapter',
    adoption_tier: 'optional'
  },
  {
    id: 'espocrm',
    name: 'EspoCRM',
    category: 'crm',
    source_type: 'open_source',
    license: 'GPL-3.0',
    maturity: 'production',
    stability_score: 88,
    default_risk_level: 'R2',
    deployment_modes: ['self_hosted', 'docker', 'php'],
    capabilities: ['contacts', 'accounts', 'opportunities', 'activities', 'workflows'],
    recommended_use: 'Stable open-source CRM adapter candidate when mature CRM semantics are needed.',
    caution_notes: 'Heavier than OPC-native CRM; use as adapter, not as primary UX.',
    adapter_status: 'http_adapter',
    adoption_tier: 'optional'
  },
  {
    id: 'suitecrm',
    name: 'SuiteCRM',
    category: 'crm',
    source_type: 'open_source',
    license: 'AGPL-3.0',
    maturity: 'production',
    stability_score: 84,
    default_risk_level: 'R2',
    deployment_modes: ['self_hosted', 'php'],
    capabilities: ['crm', 'sales_pipeline', 'workflow', 'reports'],
    recommended_use: 'Reference for complete CRM data model and workflow concepts.',
    caution_notes: 'Too heavy for default one-person-company UX.',
    adapter_status: 'manual_reference',
    adoption_tier: 'reference'
  },
  {
    id: 'odoo-community',
    name: 'Odoo Community',
    category: 'erp_crm',
    source_type: 'open_source',
    license: 'LGPL-3.0',
    maturity: 'production',
    stability_score: 86,
    default_risk_level: 'R2',
    deployment_modes: ['self_hosted', 'docker', 'python'],
    capabilities: ['crm', 'sales', 'invoicing', 'inventory', 'automation'],
    recommended_use: 'Reference or optional adapter for OPCs that need CRM plus operations.',
    caution_notes: 'Large surface area; avoid making it a hard dependency.',
    adapter_status: 'manual_reference',
    adoption_tier: 'reference'
  },
  {
    id: 'rustpbx',
    name: 'RustPBX',
    category: 'voice',
    source_type: 'open_source',
    license: 'unknown_review_required',
    maturity: 'active',
    stability_score: 82,
    default_risk_level: 'R3',
    deployment_modes: ['self_hosted', 'rust'],
    capabilities: ['pbx', 'sip', 'call_routing', 'lightweight_voice', 'call_session_webhooks'],
    recommended_use: 'Default lightweight PBX direction for OPC voice module, kept behind a RustPBX adapter boundary with approval-gated outbound calls.',
    caution_notes: 'Review license and production readiness before managed hosting; all outbound calls remain approval-gated.',
    adapter_status: 'http_adapter',
    adoption_tier: 'core'
  },
  {
    id: 'opc-native-webrtc',
    name: 'OPC Native WebRTC Boundary',
    category: 'voice',
    source_type: 'internal',
    license: 'internal',
    maturity: 'foundation',
    stability_score: 80,
    default_risk_level: 'R2',
    deployment_modes: ['built_in'],
    capabilities: ['webrtc_signaling', 'browser_voice_session', 'ice_server_config', 'agent_assist_call_console', 'recording_archive_execution'],
    recommended_use: 'Default browser-side voice session, media-sidecar, and recording-retention execution boundary that can pair with RustPBX SIP routing.',
    caution_notes: 'Keep TURN, media auth, recording archive/purge, and consent policy behind tenant-scoped config, approval, and audit guardrails before real calls.',
    adapter_status: 'native',
    adoption_tier: 'core'
  },
  {
    id: 'opc-native-smtp',
    name: 'OPC Native SMTP Email',
    category: 'email',
    source_type: 'internal',
    license: 'internal',
    maturity: 'foundation',
    stability_score: 78,
    default_risk_level: 'R3',
    deployment_modes: ['built_in'],
    capabilities: ['smtp_send', 'outbound_email', 'inbound_email_webhook'],
    recommended_use: 'Default built-in email adapter for L2 outbound; tenant brings their own SMTP credentials.',
    caution_notes: 'Outbound email requires approval, rate limits, and valid sender reputation; store credentials via integration_secret_refs / env vars only.',
    adapter_status: 'native',
    adoption_tier: 'core'
  },
  {
    id: 'opc-native-wecom',
    name: 'OPC Native WeCom Application Message',
    category: 'customer_messaging',
    source_type: 'internal',
    license: 'internal',
    maturity: 'foundation',
    stability_score: 76,
    default_risk_level: 'R3',
    deployment_modes: ['built_in'],
    capabilities: ['wecom_app_message_send', 'wecom_inbound_webhook'],
    recommended_use: 'Native WeCom work app message adapter for approved outbound messages.',
    caution_notes: 'Tenant must provide corp_id, agent_id and secret; access_token cached per tenant/agent.',
    adapter_status: 'native',
    adoption_tier: 'core'
  },
  {
    id: 'opc-ai-worker',
    name: 'OPC Python AI Worker',
    category: 'ai_pipeline',
    source_type: 'internal',
    license: 'internal',
    maturity: 'foundation',
    stability_score: 81,
    default_risk_level: 'R1',
    deployment_modes: ['sidecar', 'python'],
    capabilities: ['pain_signal_extraction', 'outreach_personalization', 'structured_ai_postprocess', 'public_source_signal_pipeline', 'staged_signal_artifacts'],
    recommended_use: 'Use as the default Python sidecar for pain-signal extraction, public-source signal pipeline staging, personalization shaping, and other offline/AI post-processing that should not live in the TS control plane.',
    caution_notes: 'Do not let this replace the TS control plane; keep it behind tenant-scoped config, audit, and artifact boundaries.',
    adapter_status: 'native',
    adoption_tier: 'core'
  },
  {
    id: 'asterisk',
    name: 'Asterisk',
    category: 'voice',
    source_type: 'open_source',
    license: 'GPL-2.0',
    maturity: 'production',
    stability_score: 94,
    default_risk_level: 'R3',
    deployment_modes: ['self_hosted', 'linux'],
    capabilities: ['pbx', 'sip', 'ivr', 'recording', 'dialplan'],
    recommended_use: 'Heavy fallback PBX candidate when RustPBX is insufficient for production requirements.',
    caution_notes: 'Operationally heavy for OPC defaults; telephony compliance, consent, recording policy, and abuse prevention required.',
    adapter_status: 'planned',
    adoption_tier: 'fallback'
  },
  {
    id: 'freeswitch',
    name: 'FreeSWITCH',
    category: 'voice',
    source_type: 'open_source',
    license: 'MPL-1.1',
    maturity: 'production',
    stability_score: 92,
    default_risk_level: 'R3',
    deployment_modes: ['self_hosted', 'linux'],
    capabilities: ['pbx', 'sip', 'webrtc', 'ivr', 'conference'],
    recommended_use: 'Heavy fallback for high-scale voice/WebRTC routing.',
    caution_notes: 'Too heavy for default OPC deployment; keep behind voice adapter boundary.',
    adapter_status: 'planned',
    adoption_tier: 'fallback'
  },
  {
    id: 'mautic',
    name: 'Mautic',
    category: 'marketing_automation',
    source_type: 'open_source',
    license: 'GPL-3.0',
    maturity: 'production',
    stability_score: 88,
    default_risk_level: 'R3',
    deployment_modes: ['self_hosted', 'docker', 'php'],
    capabilities: ['email_campaigns', 'segments', 'forms', 'lead_scoring', 'nurture'],
    recommended_use: 'Strong candidate for email nurture and marketing automation adapter.',
    caution_notes: 'Outbound email must always use approval, rate limits, and compliance checks.',
    adapter_status: 'http_adapter',
    adoption_tier: 'optional'
  },
  {
    id: 'chatwoot',
    name: 'Chatwoot',
    category: 'customer_messaging',
    source_type: 'open_source',
    license: 'MIT',
    maturity: 'production',
    stability_score: 90,
    default_risk_level: 'R3',
    deployment_modes: ['self_hosted', 'docker', 'rails'],
    capabilities: ['inbox', 'live_chat', 'conversation_assignment', 'customer_timeline'],
    recommended_use: 'Stable open-source inbox/customer messaging adapter target.',
    caution_notes: 'Customer messaging is external action; route sends through approval.',
    adapter_status: 'http_adapter',
    adoption_tier: 'core'
  },
  {
    id: 'listmonk',
    name: 'Listmonk',
    category: 'email_newsletter',
    source_type: 'open_source',
    license: 'AGPL-3.0',
    maturity: 'production',
    stability_score: 86,
    default_risk_level: 'R3',
    deployment_modes: ['self_hosted', 'docker', 'go'],
    capabilities: ['newsletter', 'lists', 'campaigns', 'templates'],
    recommended_use: 'Newsletter and broadcast email adapter candidate.',
    caution_notes: 'AGPL and outbound email compliance review required.',
    adapter_status: 'http_adapter',
    adoption_tier: 'optional'
  },
  {
    id: 'posthog',
    name: 'PostHog',
    category: 'analytics',
    source_type: 'open_source',
    license: 'MIT',
    maturity: 'production',
    stability_score: 92,
    default_risk_level: 'R1',
    deployment_modes: ['cloud', 'self_hosted'],
    capabilities: ['product_analytics', 'events', 'funnels', 'session_replay', 'feature_flags'],
    recommended_use: 'Primary analytics integration candidate for event/funnel instrumentation.',
    caution_notes: 'PII minimization and tenant isolation required.',
    adapter_status: 'http_adapter',
    adoption_tier: 'core'
  },
  {
    id: 'plausible',
    name: 'Plausible',
    category: 'web_analytics',
    source_type: 'open_source',
    license: 'AGPL-3.0',
    maturity: 'production',
    stability_score: 88,
    default_risk_level: 'R1',
    deployment_modes: ['cloud', 'self_hosted'],
    capabilities: ['web_analytics', 'privacy_friendly_tracking'],
    recommended_use: 'Privacy-friendly web analytics reference or adapter.',
    caution_notes: 'Use alongside internal event model, not as only source of truth.',
    adapter_status: 'manual_reference',
    adoption_tier: 'optional'
  },
  {
    id: 'umami',
    name: 'Umami',
    category: 'web_analytics',
    source_type: 'open_source',
    license: 'MIT',
    maturity: 'production',
    stability_score: 86,
    default_risk_level: 'R1',
    deployment_modes: ['cloud', 'self_hosted'],
    capabilities: ['web_analytics', 'privacy_friendly_tracking'],
    recommended_use: 'Lightweight web analytics adapter/reference.',
    caution_notes: 'Not a full attribution engine.',
    adapter_status: 'manual_reference',
    adoption_tier: 'optional'
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: 'workflow_automation',
    source_type: 'open_source',
    license: 'Sustainable Use License',
    maturity: 'production',
    stability_score: 90,
    default_risk_level: 'R2',
    deployment_modes: ['cloud', 'self_hosted', 'docker'],
    capabilities: ['workflow_automation', 'connectors', 'webhooks', 'scheduling'],
    recommended_use: 'Backend automation engine reference/optional worker for advanced workflows.',
    caution_notes: 'Do not expose raw n8n complexity to OPC users by default.',
    adapter_status: 'planned',
    adoption_tier: 'optional'
  },
  {
    id: 'activepieces',
    name: 'Activepieces',
    category: 'workflow_automation',
    source_type: 'open_source',
    license: 'MIT',
    maturity: 'active',
    stability_score: 82,
    default_risk_level: 'R2',
    deployment_modes: ['cloud', 'self_hosted', 'docker'],
    capabilities: ['workflow_automation', 'connectors', 'webhooks'],
    recommended_use: 'Open connector ecosystem reference; evaluate as lower-code adapter layer.',
    caution_notes: 'Connector quality varies; each external action needs policy checks.',
    adapter_status: 'planned',
    adoption_tier: 'optional'
  },
  {
    id: 'calcom',
    name: 'Cal.com',
    category: 'scheduling',
    source_type: 'open_source',
    license: 'AGPL-3.0',
    maturity: 'production',
    stability_score: 88,
    default_risk_level: 'R2',
    deployment_modes: ['cloud', 'self_hosted'],
    capabilities: ['booking', 'calendar', 'routing_forms', 'availability'],
    recommended_use: 'Scheduling adapter for demo/consultation booking.',
    caution_notes: 'Calendar data needs privacy and scoped token handling.',
    adapter_status: 'http_adapter',
    adoption_tier: 'core'
  },
  {
    id: 'formbricks',
    name: 'Formbricks',
    category: 'forms_surveys',
    source_type: 'open_source',
    license: 'AGPL-3.0',
    maturity: 'production',
    stability_score: 84,
    default_risk_level: 'R1',
    deployment_modes: ['cloud', 'self_hosted'],
    capabilities: ['forms', 'surveys', 'feedback', 'lead_capture'],
    recommended_use: 'Form/survey inspiration and optional lead capture adapter.',
    caution_notes: 'Form submissions must normalize into raw_inquiry/lead objects.',
    adapter_status: 'planned',
    adoption_tier: 'optional'
  },
  {
    id: 'perplexica',
    name: 'Perplexica / Vane',
    category: 'ai_search',
    source_type: 'open_source',
    license: 'MIT',
    maturity: 'active',
    stability_score: 78,
    default_risk_level: 'R1',
    deployment_modes: ['self_hosted', 'docker'],
    capabilities: ['ai_search', 'citations', 'research', 'domain_search', 'competitive_intel', 'market_discovery'],
    recommended_use: 'Tenant-scoped AI search provider candidate for clue discovery, market research, and citation-backed follow-up investigation.',
    caution_notes: 'Use for discovery and evidence gathering, not as the final source of truth; route outputs back into OPC artifacts/wiki for review.',
    adapter_status: 'http_adapter',
    adoption_tier: 'optional'
  },
  {
    id: 'open-notebook',
    name: 'Open Notebook',
    category: 'notebook_workspace',
    source_type: 'open_source',
    license: 'MIT',
    maturity: 'active',
    stability_score: 81,
    default_risk_level: 'R1',
    deployment_modes: ['self_hosted', 'docker', 'api'],
    capabilities: ['notebook_workspace', 'multi_modal_notebook', 'citation_chat', 'podcast_generation', 'research_notes', 'rest_api'],
    recommended_use: 'Optional tenant notebook workspace provider for cited notebook Q&A, multimodal source grouping, and audio overview generation.',
    caution_notes: 'Do not replace the tenant-scoped OPC wiki/memory source of truth; use as a notebook layer on top of existing sources and artifacts.',
    adapter_status: 'http_adapter',
    adoption_tier: 'optional'
  },
  {
    id: 'amap-place-search',
    name: 'Amap Place Search',
    category: 'geo_business_data',
    source_type: 'external_api',
    license: 'commercial_api',
    maturity: 'production',
    stability_score: 86,
    default_risk_level: 'R1',
    deployment_modes: ['api'],
    capabilities: ['place_search', 'business_profile', 'business_reviews', 'geo_coordinates', 'route_matrix'],
    recommended_use: 'Primary China-market geo lead discovery provider slot for local business search, business profile enrichment, and route planning.',
    caution_notes: 'Use only through tenant-scoped provider config and approval-safe downstream actions; do not treat returned emails or phones as consent to contact.',
    adapter_status: 'planned',
    adoption_tier: 'optional'
  },
  {
    id: 'baidu-place-search',
    name: 'Baidu Place Search',
    category: 'geo_business_data',
    source_type: 'external_api',
    license: 'commercial_api',
    maturity: 'production',
    stability_score: 84,
    default_risk_level: 'R1',
    deployment_modes: ['api'],
    capabilities: ['place_search', 'business_profile', 'business_reviews', 'geo_coordinates', 'route_matrix'],
    recommended_use: 'Secondary China-market geo lead discovery provider slot and redundancy path for local business search and review enrichment.',
    caution_notes: 'Keep provider-specific quotas, attribution rules, and downstream compliance checks in tenant policy/config, not hardcoded business logic.',
    adapter_status: 'planned',
    adoption_tier: 'optional'
  },
  {
    id: 'llm-wiki',
    name: 'LLM Wiki',
    category: 'knowledge_base',
    source_type: 'open_source',
    license: 'review_required',
    maturity: 'active',
    stability_score: 80,
    default_risk_level: 'R1',
    deployment_modes: ['desktop', 'self_hosted', 'markdown_repo'],
    capabilities: ['llm_wiki', 'knowledge_base', 'markdown_pages', 'graph_view', 'index_log', 'wiki_lint'],
    recommended_use: 'Reference pattern for OPC native wiki: raw immutable sources, LLM-maintained markdown pages, index.md/log.md, query and lint loops.',
    caution_notes: 'Use as architecture inspiration/reference; review license before embedding code. OPC should keep its own tenant-scoped wiki runtime.',
    adapter_status: 'manual_reference',
    adoption_tier: 'reference'
  },
  {
    id: 'anythingllm',
    name: 'AnythingLLM',
    category: 'rag',
    source_type: 'open_source',
    license: 'MIT',
    maturity: 'production',
    stability_score: 84,
    default_risk_level: 'R1',
    deployment_modes: ['self_hosted', 'desktop', 'docker'],
    capabilities: ['rag', 'workspace_knowledge', 'documents'],
    recommended_use: 'Knowledge/RAG adapter candidate for tenant knowledge bases.',
    caution_notes: 'Tenant data isolation and retrieval evidence tracking required.',
    adapter_status: 'planned',
    adoption_tier: 'optional'
  },
  {
    id: 'openai-compatible',
    name: 'OpenAI-Compatible Model Provider',
    category: 'model_provider',
    source_type: 'external_api',
    license: 'tenant_contract_required',
    maturity: 'production',
    stability_score: 84,
    default_risk_level: 'R1',
    deployment_modes: ['api', 'self_hosted_gateway'],
    capabilities: ['chat_completion', 'model_gateway', 'byok', 'fallback_model', 'structured_output'],
    recommended_use: 'Generic live model-provider adapter for OpenAI-compatible APIs, including tenant BYOK setups and self-hosted gateways.',
    caution_notes: 'Tenant must configure endpoint and secret refs; model output still goes through OPC trace, quota, artifacts, and review layers.',
    adapter_status: 'http_adapter',
    adoption_tier: 'core'
  },
  {
    id: 'open-webui',
    name: 'Open WebUI',
    category: 'llm_ui',
    source_type: 'open_source',
    license: 'BSD-3-Clause',
    maturity: 'production',
    stability_score: 86,
    default_risk_level: 'R1',
    deployment_modes: ['self_hosted', 'docker'],
    capabilities: ['llm_ui', 'model_gateway', 'tools'],
    recommended_use: 'Reference for model gateway and admin/operator LLM UX.',
    caution_notes: 'OPC should not outsource core runtime state to a chat UI.',
    adapter_status: 'manual_reference',
    adoption_tier: 'reference'
  },
  {
    id: 'ragflow',
    name: 'RAGFlow',
    category: 'rag',
    source_type: 'open_source',
    license: 'Apache-2.0',
    maturity: 'active',
    stability_score: 78,
    default_risk_level: 'R1',
    deployment_modes: ['self_hosted', 'docker'],
    capabilities: ['rag', 'document_parsing', 'knowledge_base'],
    recommended_use: 'Document-heavy RAG pipeline reference and potential adapter.',
    caution_notes: 'Operationally heavier than simple tenant memory; use selectively.',
    adapter_status: 'planned',
    adoption_tier: 'optional'
  },
  {
    id: 'changedetection',
    name: 'changedetection.io',
    category: 'competitive_intel',
    source_type: 'open_source',
    license: 'Apache-2.0',
    maturity: 'production',
    stability_score: 86,
    default_risk_level: 'R1',
    deployment_modes: ['self_hosted', 'docker'],
    capabilities: ['website_monitoring', 'change_detection', 'alerts'],
    recommended_use: 'Competitor monitoring adapter candidate.',
    caution_notes: 'Respect robots, rate limits, and website terms.',
    adapter_status: 'planned',
    adoption_tier: 'optional'
  },
  {
    id: 'mcp-github',
    name: 'GitHub MCP Server',
    category: 'mcp',
    source_type: 'mcp_server',
    license: 'varies',
    maturity: 'production',
    stability_score: 86,
    default_risk_level: 'R2',
    deployment_modes: ['local', 'remote'],
    capabilities: ['repository', 'issues', 'pull_requests', 'actions'],
    recommended_use: 'Development and integration workflow MCP server.',
    caution_notes: 'Token scopes must be minimized; writes need approval.',
    adapter_status: 'mcp',
    adoption_tier: 'optional'
  },
  {
    id: 'mcp-postgres',
    name: 'Postgres MCP Server',
    category: 'mcp',
    source_type: 'mcp_server',
    license: 'varies',
    maturity: 'active',
    stability_score: 78,
    default_risk_level: 'R2',
    deployment_modes: ['local', 'remote'],
    capabilities: ['database_read', 'database_write', 'schema_inspection'],
    recommended_use: 'Database inspection MCP server for admin/operator workflows.',
    caution_notes: 'Writes and broad reads require strict tenant isolation and approval.',
    adapter_status: 'mcp',
    adoption_tier: 'optional'
  },
  {
    id: 'mcp-playwright',
    name: 'Playwright MCP Server',
    category: 'mcp',
    source_type: 'mcp_server',
    license: 'varies',
    maturity: 'active',
    stability_score: 82,
    default_risk_level: 'R2',
    deployment_modes: ['local', 'remote'],
    capabilities: ['browser_automation', 'screenshots', 'page_testing'],
    recommended_use: 'Browser validation for landing pages, forms, competitor evidence, and QA.',
    caution_notes: 'External site interaction can become high risk; sandbox sessions required.',
    adapter_status: 'mcp',
    adoption_tier: 'core'
  }
];

export const defaultSkillCatalog: IntegrationCatalogEntry[] = [
  {
    id: 'skill.lead_qualification',
    name: 'Lead Qualification SOP',
    category: 'lead',
    source_type: 'skill',
    maturity: 'stable',
    stability_score: 90,
    default_risk_level: 'R1',
    capabilities: ['lead_scoring', 'routing', 'next_action'],
    recommended_use: 'Reusable skill for raw inquiry to qualified lead/opportunity routing.',
    caution_notes: 'Do not auto-send external messages from this skill.',
    adapter_status: 'native',
    adoption_tier: 'core'
  },
  {
    id: 'skill.weekly_review',
    name: 'Weekly Growth Review SOP',
    category: 'analytics',
    source_type: 'skill',
    maturity: 'stable',
    stability_score: 90,
    default_risk_level: 'R1',
    capabilities: ['weekly_report', 'funnel_review', 'next_best_actions'],
    recommended_use: 'Reusable weekly review and recommendation skill.',
    caution_notes: 'Recommendations should cite metrics/artifacts.',
    adapter_status: 'native',
    adoption_tier: 'core'
  },
  {
    id: 'skill.crm_followup',
    name: 'CRM Follow-up SOP',
    category: 'crm',
    source_type: 'skill',
    maturity: 'stable',
    stability_score: 88,
    default_risk_level: 'R2',
    capabilities: ['task_creation', 'followup_prioritization', 'sla'],
    recommended_use: 'Reusable follow-up task creation and SLA policy skill.',
    caution_notes: 'Customer-facing messages still require approval.',
    adapter_status: 'native',
    adoption_tier: 'core'
  }
];
