server_name: converact-nats-acceptance
port: 4222
monitor_port: 8222

authorization {
  user: $NATS_CLIENT_USER
  password: $NATS_CLIENT_PASSWORD
  timeout: 2
}

jetstream {
  store_dir: /data/jetstream
  max_memory_store: 256MB
  max_file_store: 1GB
}
