-- Projection pointer only. Do not add executable DDL here.
--
-- The authoritative rolling migrations are:
--   src/migrations/107_ivekit_sip_effect_oracle.sql
--   src/migrations/113_converact_sip_effect_transport_completed.sql
--   src/migrations/114_converact_sip_effect_transport_completed_validate.sql
--
-- Keeping a single executable source prevents drift between the application
-- migration runner, standalone packaging and SIP-foundation documentation.
