#!/bin/sh

CONVERACT_VALIDATION_SERVER_IP='101.42.7.139'
CONVERACT_VALIDATION_SSH_USER='ubuntu'
CONVERACT_VALIDATION_SSH_TARGET="${CONVERACT_VALIDATION_SSH_USER}@${CONVERACT_VALIDATION_SERVER_IP}"

readonly CONVERACT_VALIDATION_SERVER_IP
readonly CONVERACT_VALIDATION_SSH_USER
readonly CONVERACT_VALIDATION_SSH_TARGET
