apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: converact-postgres-rw-pooler
  labels:
    app.kubernetes.io/name: converact-postgres-rw-pooler
    app.kubernetes.io/part-of: converact-platform
spec:
  minAvailable: 2
  selector:
    matchLabels:
      cnpg.io/poolerName: converact-postgres-rw-pooler
