apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opc-postgres-rw-pooler
  labels:
    app.kubernetes.io/name: opc-postgres-rw-pooler
    app.kubernetes.io/part-of: ivekit-platform
spec:
  minAvailable: 2
  selector:
    matchLabels:
      cnpg.io/poolerName: opc-postgres-rw-pooler
